### ISSUE TITLE
Providers not respecting order defined

### ISSUE THREAD

**Issue by AndrewSB** [immobiliare/RealFlags#23]
### Bug Report

| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no |
| Version             | 1.3.1  |

#### Summary

I'm setting `providers: [FeatureFlagLocalProvider(), FirebaseRemoteProvider()]`. for this property

default: True
localProvider: True
firebase: False

#### Current behavior

The flag resolves as false, somehow deciding to choose firebase over the localProvider

#### How to reproduce

unsure, it seems like it should just work if you do [localProvider, firebaseProvider]

#### Expected behavior

the flag should resolve as True, respecting the local provider over the firebase provider

**Comment by malcommac** [comment]
Hi, Are you previously initialized Firebase?

**Comment by AndrewSB** [comment]
we run 

```
FirebaseApp.configure()
```

separately, yes. is that not recommended? we also use firebase to send up analytics events

**Comment by AndrewSB** [comment]
i believe this is happening after just the first few seconds after launch. i was seeing that case i mention above in the feature flag browser UI.

but as i'm trying to reproduce this issue, it doesn't seem to come up again. it seems to be using the value from the local provider correctly, even when it's different than what's in firebase. if i see it again, i'll re-open this with more detail
